### ISSUE TITLE
Bug In Lesson 3, Exercise 3 Solution

### ISSUE THREAD

**Issue by ericwilliamsneu** [udacity/SFND_Camera#3]
Team, it appears the solution for the exercise "Estimating TTC with a Camera" has a bug in the code. I was attempting to build and run the solution file to verify the result I got with my code, but unfortunately the solution has a compile error.

# Steps to reproduce

1. Replace exercise template file "compute_ttc_camera.cpp" with provided solution file.
2. Run CMake configure and CMake build

# Expected Outcome

1. Project builds successfully

# Observed Outcome

1. Build error occurs, error details below.

# Error Details
`[main] Configuring folder: TTC_camera 
[proc] Executing command: /usr/bin/cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/bin/x86_64-linux-gnu-gcc-9 -DCMAKE_CXX_COMPILER:FILEPATH=/bin/x86_64-linux-gnu-g++-9 "-H/home/eric/src/SFND_Camera/Lesson 3 - Engineering a Collision Detection System/Estimating TTC with Camera/TTC_camera" "-B/home/eric/src/SFND_Camera/Lesson 3 - Engineering a Collision Detection System/Estimating TTC with Camera/TTC_camera/build" -G "Unix Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] -- Configuring done
[cmake] -- Generating done
[cmake] -- Build files have been written to: /home/eric/src/SFND_Camera/Lesson 3 - Engineering a Collision Detection System/Estimating TTC with Camera/TTC_camera/build
[main] Building folder: TTC_camera compute_ttc_camera
[build] Starting build
[proc] Executing command: /usr/bin/cmake --build "/home/eric/src/SFND_Camera/Lesson 3 - Engineering a Collision Detection System/Estimating TTC with Camera/TTC_camera/build" --config Debug --target compute_ttc_camera -- -j 6
[build] Scanning dependencies of target compute_ttc_camera
[build] [ 33%] Building CXX object CMakeFiles/compute_ttc_camera.dir/src/compute_ttc_camera_solution.cpp.o
[build] /home/eric/src/SFND_Camera/Lesson 3 - Engineering a Collision Detection System/Estimating TTC with Camera/TTC_camera/src/compute_ttc_camera_solution.cpp: In function ‘void computeTTCCamera(std::vector<cv::KeyPoint>&, std::vector<cv::KeyPoint>&, std::vector<cv::DMatch>, double, double&)’:
[build] /home/eric/src/SFND_Camera/Lesson 3 - Engineering a Collision Detection System/Estimating TTC with Camera/TTC_camera/src/compute_ttc_camera_solution.cpp:59:5: error: ‘dT’ was not declared in this scope
[build]    59 |     dT = 1 / frameRate;
[build]       |     ^~
[build] make[3]: *** [CMakeFiles/compute_ttc_camera.dir/build.make:63: CMakeFiles/compute_ttc_camera.dir/src/compute_ttc_camera_solution.cpp.o] Error 1
[build] make[2]: *** [CMakeFiles/Makefile2:76: CMakeFiles/compute_ttc_camera.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/compute_ttc_camera.dir/rule] Error 2
[build] make: *** [Makefile:118: compute_ttc_camera] Error 2
[build] Build finished with exit code 2`

# Assessment

- dT is not declared in the scope it is used.
- The line `double dT = 1 / frameRate;` has been incorrectly removed from the solution code.

# Recommended Fix

- Declare dT in the scope of the computeTTCCamera() function as such: `double dT = 1 / frameRate;`

**Comment by abhiojha8** [comment]
resolved.
