### ISSUE TITLE
lesson6 lidar data doesn't show properly

### ISSUE THREAD

**Issue by tmiao2** [udacity/SFND_Camera#6]
Hi, when i build with your solution with visual studio 2015. and it compiles well, but after i run the generated binary file. The top view of lidar data doesn't show properly. 
and i tried to debug, it looks all lidar data are close to Point zero. 
Can you tell me how to fix it?

**Comment by abhiojha8** [comment]
Please reach out to mentors in the Knowledge Hub for this issue. Thanks :)
